export class Account {
    constructor(
        public id?: bigint,
        public username?: string,
        private password?: string,
        public fullName?: string,
        public imageUrl?: string,
        public lastAccess?: Date,
        public createdDate?: Date,
        public phoneNumber?: string,
        public userType?: string,
        public address?: string,
        public university?: string,
        public graduatedYear?: bigint,
        public isLeader?: boolean,
        public isManager?: boolean,
        public isActived?: boolean,
        public birthday?: Date,
        public skypeAccount?: string,
        public email?: string,
        public isApproved?: boolean,
        public roleId?: number,
        public roleName?: string,
        public departmentId?: number,
        public departmentName?: string,
        public positionId?: number,
        public positionName?: string,
        public teamId?: number,
        public teamName?: string,

        public rememberMe?: boolean,
        public authorities?: string[],

        public langKey?: string,
        public flag?: string,
        public login?: string,

        // public activated?: boolean,
        // public authorities?: string[],
        // public email?: string,
        // public firstName?: string,
        // public lastName?: string,
        // public imageUrl?: string,
        // public emp_code?: string,
        // public emp_name?: string,
        // public ipphone?: string,
        // public isDelegate?: string,
        public job_title?: string,
        // public job_type?: string,
        // public org_name?: string,
        // public type?: string,
    ) {
    }
}
